name = "md2tasks"
description = "Use this prompt to convert all tasks from markdown format to tasks.json format."
prompt = """Execute one of the follow commands to convert all tasks from markdown format to tasks.json format.
python3 .github/prompts/scripts/convert_tasks.py --to_tasks
python3 $HOME/.gemini/commands/scripts/convert_tasks.py --to_tasks
"""
