#!/usr/bin/python3
"""PostToolUse hook: flag newly added comments without a declared reason.

Runs after Edit/Write/MultiEdit; checks why:/hazard:/invariant: markers.
Non-blocking — emits additionalContext for the agent to self-correct,
mirrors the exemption ordering and MVP scope from the porting guide
(marker check before generated-banner exemption; no resolvable-context
or doc-restates-name checks).
"""

import difflib
import json
from pathlib import Path
import re
import sys

sys.path.insert(0, str(Path(__file__).parent))
from utils import (
    _EXT_TO_TS_LANG,
    _get_ts_parser,
    get_by_key,
    get_hooks_logger,
    minify_json,
)

LOG = get_hooks_logger("CommentPolicyHint")

MAX_DECLARED_LINES = 4
MARKER_RE = re.compile(
    r"^\s*(?://|#|/\*|\*)?\s*(why|hazard|invariant)\s*:", re.IGNORECASE
)
DIRECTIVE_RE = re.compile(
    r"(eslint-disable|noqa|type:\s*ignore|pragma|prettier-ignore|istanbul ignore|#!)",
    re.IGNORECASE,
)
GENERATED_RE = re.compile(
    r"(@generated|do not edit|autogenerated|auto-generated)", re.IGNORECASE
)


def comment_lines(content: str, file_path: str) -> list[tuple[int, str]]:
    """Line number (1-based) + text for every comment node in the file.

    Args:
        content: full source text to scan.
        file_path: used only to resolve the tree-sitter language by extension.

    Returns:
        (line_number, comment_text) pairs, sorted ascending by line.
    """
    lang = _EXT_TO_TS_LANG.get(Path(file_path).suffix)
    if not lang or not content.strip():
        return []
    parser = _get_ts_parser(lang)
    if parser is None:
        return []
    try:
        tree = parser.parse(content.encode("utf-8", errors="ignore"))
    # tree-sitter's C binding raises assorted/undocumented types per language
    except Exception:  # pylint: disable=broad-exception-caught
        return []

    out: list[tuple[int, str]] = []
    stack = [tree.root_node]
    try:
        while stack:
            node = stack.pop()
            if node.type == "comment":
                text = node.text.decode("utf-8", errors="ignore")
                out.append((node.start_point[0] + 1, text))
                continue
            stack.extend(node.children)
    # same as above: tree-sitter can raise assorted/undocumented types
    except Exception:  # pylint: disable=broad-exception-caught
        return []
    out.sort(key=lambda item: item[0])
    return out


def group_blocks(lines: list[tuple[int, str]]) -> list[list[tuple[int, str]]]:
    """Group consecutive comment lines into blocks.

    Args:
        lines: (line_number, text) pairs, ascending by line number.

    Returns:
        Blocks of consecutive comment lines, in encounter order.
    """
    blocks: list[list[tuple[int, str]]] = []
    for line_no, text in lines:
        if blocks and blocks[-1][-1][0] == line_no - 1:
            blocks[-1].append((line_no, text))
        else:
            blocks.append([(line_no, text)])
    return blocks


def judge_block(block: list[tuple[int, str]]) -> str | None:
    """Judge one comment block against the declared-reason policy.

    Args:
        block: consecutive (line_number, text) pairs making up one comment.

    Returns:
        A violation reason string, or None if the block is exempt or declared.
    """
    first_text = block[0][1]

    if DIRECTIVE_RE.search(first_text):
        return None
    if GENERATED_RE.search(first_text) and not MARKER_RE.search(first_text):
        return None

    if not MARKER_RE.search(first_text):
        return "undeclared comment — no why:/hazard:/invariant: marker"
    if len(block) > MAX_DECLARED_LINES:
        return f"declared comment too long ({len(block)} lines > {MAX_DECLARED_LINES})"
    return None


def added_line_numbers(old_content: str, new_content: str) -> set[int]:
    """Line numbers (1-based, in new_content) new relative to old_content.

    Line-level diff via difflib, no git needed — compares this edit's
    before/after content directly.

    Args:
        old_content: file content before the edit.
        new_content: file content after the edit.

    Returns:
        Line numbers (in new_content) touched by an insert or replace.
    """
    old_lines = old_content.splitlines()
    new_lines = new_content.splitlines()
    matcher = difflib.SequenceMatcher(a=old_lines, b=new_lines, autojunk=False)
    added: set[int] = set()
    for tag, _, _, j1, j2 in matcher.get_opcodes():
        if tag in ("insert", "replace"):
            added.update(range(j1 + 1, j2 + 1))
    return added


def find_findings(old_content: str, new_content: str, file_path: str) -> list[dict]:
    """Violations among comment blocks touched by this edit.

    Args:
        old_content: file content before the edit.
        new_content: file content after the edit.
        file_path: used to resolve the tree-sitter language by extension.

    Returns:
        One dict per violation: line, reason, snippet.
    """
    added = added_line_numbers(old_content, new_content)
    if not added:
        return []

    blocks = group_blocks(comment_lines(new_content, file_path))
    findings = []
    for block in blocks:
        if not any(ln in added for ln, _ in block):
            continue
        reason = judge_block(block)
        if reason:
            start_line = block[0][0]
            snippet = block[0][1].strip()[:80]
            findings.append({"line": start_line, "reason": reason, "snippet": snippet})
    return findings


def content_pair_for_edit(
    tool_name: str, tool_input: dict | None, file_path: str
) -> tuple[str, str] | None:
    """(old_content, new_content) for this edit, from the payload itself.

    No git required — sidesteps HEAD-diff staleness entirely.

    Args:
        tool_name: "Edit", "MultiEdit", or "Write".
        tool_input: the hook payload's tool_input; may be None.
        file_path: path of the file that was edited/written.

    Returns:
        (old_content, new_content), or None if content can't be reconstructed.
    """
    try:
        new_content = Path(file_path).read_text(encoding="utf-8")
    except OSError:
        return None

    if tool_name == "Write":
        return "", new_content

    if tool_input is None:
        return None
    edits = tool_input.get("edits") if tool_name == "MultiEdit" else [tool_input]
    if not edits:
        return None

    old_content = new_content
    for edit in reversed(edits):
        new_string = edit.get("new_string") or ""
        old_string = edit.get("old_string") or ""
        if new_string and new_string in old_content:
            old_content = old_content.replace(new_string, old_string, 1)

    return old_content, new_content


def build_output(file_path: str, findings: list[dict]) -> dict:
    """PostToolUse additionalContext payload for the given findings.

    Args:
        file_path: path of the file the findings belong to.
        findings: violation dicts from find_findings.

    Returns:
        The hookSpecificOutput envelope for PostToolUse.
    """
    return {
        "hookSpecificOutput": {
            "hookEventName": "PostToolUse",
            "additionalContext": minify_json(
                {
                    "instruction": (
                        f"HEADS UP: {len(findings)} comment(s) added without a "
                        "declared reason — delete them, or restate with "
                        "why:/hazard:/invariant: (this is a hint, not a block; "
                        "cheaper to fix now)"
                    ),
                    "file": file_path,
                    "findings": findings,
                }
            ),
        }
    }


def main() -> None:
    """Entry point: read the PostToolUse payload, emit findings if any."""
    try:
        payload = json.load(sys.stdin)
    except (json.JSONDecodeError, EOFError) as e:
        LOG.debug("Failed to parse stdin JSON: %s", e)
        sys.exit(0)

    try:
        tool_name = get_by_key(payload, "tool_name")
        if tool_name not in ("Edit", "MultiEdit", "Write"):
            sys.exit(0)

        tool_input = get_by_key(payload, "tool_input")
        file_path = get_by_key(tool_input, "file_path") if tool_input else None
        if not file_path or Path(file_path).suffix not in _EXT_TO_TS_LANG:
            sys.exit(0)

        pair = content_pair_for_edit(tool_name, tool_input, file_path)
        if pair is None:
            sys.exit(0)
        old_content, new_content = pair

        findings = find_findings(old_content, new_content, file_path)
        if not findings:
            sys.exit(0)

        output = build_output(file_path, findings)
        dumped = json.dumps(output, ensure_ascii=False)
        LOG.debug("[additionalContext]: %s", dumped[:500])
        print(dumped)  # noqa: T201 — PostToolUse output contract requires stdout

    except Exception as e:  # pylint: disable=broad-exception-caught
        # hook must never crash the agent turn
        LOG.warning("Unexpected error: %s: %s", type(e).__name__, e, exc_info=True)

    sys.exit(0)


if __name__ == "__main__":
    main()
